<a href="https://colab.research.google.com/github/MarcelodeFreitas/udemy_deep_learning_pytorch_python/blob/main/Projeto_5_Classifica%C3%A7%C3%A3o_bin%C3%A1ria_breast_cancer_carregar_o_classificador.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto 5: Classificação binária brest cancer - carregar o classificador

## Etapa 1: Importação das bibliotecas

In [11]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import accuracy_score
torch.__version__

'1.13.1+cpu'

## Etapa 2: Carregamento do classificador

In [12]:
np.random.seed(123)
torch.manual_seed(123)

In [13]:
class classificador_torch(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense0 = nn.Linear(30, 8)
        torch.nn.init.normal_(self.dense0.weight, mean = 0.0, std = 0.05)
        self.dense1 = nn.Linear(8, 8)
        torch.nn.init.normal_(self.dense1.weight, mean = 0.0, std = 0.05)
        self.dense2 = nn.Linear(8, 1)
        self.activation = nn.ReLU()
        self.dropout = nn.Dropout(0.2)
        self.output = nn.Sigmoid()

    def forward(self, X):
        X = self.dense0(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense1(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense2(X)
        X = self.output(X)
        return X

In [14]:
classificador = classificador_torch()

In [15]:
state_dict = torch.load('checkpoint.pth')

In [16]:
state_dict

OrderedDict([('dense0.weight',
              tensor([[-6.4070e-01, -1.2105e-02, -3.9366e-01, -1.0184e-01,  8.3805e-02,
                       -5.0670e-02,  5.2164e-02, -5.6332e-02,  4.0225e-02,  8.9479e-02,
                       -1.8339e-02,  2.4520e-03,  7.8185e-04, -1.7233e-02,  2.6877e-02,
                        2.3057e-01, -3.7470e-01, -3.0753e-01, -1.0798e-01,  4.3265e-01,
                       -4.8195e-01,  2.3206e-02, -3.2733e-01,  1.8466e-01,  3.0953e-02,
                        3.9079e-02,  2.1703e-02,  6.3821e-02,  1.7347e-02,  6.6465e-01],
                      [ 7.5206e-02,  1.4571e-02,  5.1368e-02, -5.0353e-02,  1.0085e-01,
                        3.4654e-02,  7.1073e-02, -1.4861e-03, -3.9469e-02, -3.5528e-02,
                        2.8993e-02, -2.2005e-03, -4.1547e-02,  7.9065e-02, -1.4188e-09,
                        2.0390e-06,  2.0629e-02, -6.4045e-09, -2.2665e-08,  2.7463e-09,
                       -8.1432e-02,  4.5196e-02, -4.9173e-02, -4.8898e-02, -7.0585e-02,


In [17]:
classificador.load_state_dict(state_dict)

<All keys matched successfully>

## Etapa 3: Previsões


In [18]:
novo = torch.tensor([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                      0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                      0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                      0.84, 158, 0.363]])

In [19]:
classificador.eval()
previsao = classificador(novo)
previsao = (previsao.detach().numpy() > 0.5)
previsao

array([[ True]])

In [20]:
previsores = pd.read_csv('./databases/entradas_breast.csv')
classe = pd.read_csv('./databases/saidas_breast.csv')

In [21]:
previsores = torch.tensor(np.array(previsores), dtype = torch.float)
classe = torch.tensor(np.array(classe), dtype = torch.float)

In [22]:
previsoes = classificador.forward(previsores).detach()

In [23]:
previsoes

tensor([[6.8036e-09],
        [9.7987e-07],
        [3.1887e-05],
        [9.5995e-07],
        [1.0857e-03],
        [3.7398e-01],
        [1.2628e-06],
        [5.6600e-02],
        [9.9154e-02],
        [3.4576e-04],
        [1.6617e-02],
        [2.8806e-04],
        [2.0614e-01],
        [7.9430e-01],
        [8.8552e-01],
        [1.7901e-01],
        [3.6504e-03],
        [1.1560e-04],
        [1.0950e-11],
        [8.7935e-01],
        [8.3780e-01],
        [1.0000e+00],
        [2.3568e-01],
        [3.9243e-12],
        [7.8166e-12],
        [2.3985e-05],
        [3.0686e-01],
        [8.5746e-04],
        [8.3884e-05],
        [6.2600e-02],
        [2.9918e-05],
        [1.2462e-02],
        [9.4163e-04],
        [5.8247e-07],
        [6.9170e-04],
        [2.0592e-02],
        [5.2094e-01],
        [9.9997e-01],
        [1.3097e-01],
        [5.6411e-01],
        [5.0029e-01],
        [9.2871e-01],
        [1.7814e-06],
        [5.8750e-02],
        [7.6515e-01],
        [4

In [24]:
F.binary_cross_entropy(previsoes, classe).numpy()

array(0.16026758, dtype=float32)

In [25]:
accuracy_score(classe.numpy(), (previsoes > 0.5).numpy())

0.9349736379613357